config/routes.rb
Rails.application.routes.draw do
  
  root 'layouts#index'

  # various course listings
  get '/courses/free', to: 'courses#free', as: 'courses_free'
  get '/courses/featured', to: 'courses#featured', as: 'courses_featured'
  get '/courses/featured/free', to: 'courses#featured_free', as: 'courses_featured_free'
  
  resources :courses do
    resources :comments
  end

  resources :users
  resources :teachers, controller: 'users'
  resources :students, controller: 'users'

  resources :interactions #TODO remove
  resources :announcements, controller: 'interactions'
  resources :assignments, controller: 'interactions'
  resources :responses #TODO remove
  resources :questions, controller: 'responses'
  resources :completed_assignments, controller: 'responses'

  get '/welcome', to: 'layouts#welcome'

  get '/signin', to: 'users#signin'

  get '/signout', to: 'users#signout'

  get '/post_signin', to: 'users#post_signin'

  get '/signup', to:'users#new'

  #randomize user avatar
  get '/users/:id/randomize_avatar', to: 'users#randomize_avatar'

  # new announcement/assignment for a course
  get '/announcements/:course_id/new', to: 'interactions#new', as: 'announcements_course_new'
  get '/assignments/:course_id/new', to: 'interactions#new', as: 'assignments_course_new'
  
  # new question/completed_assignment for an interaction (assignment/announcement)
  get '/questions/:announcement_id/new', to: 'responses#new', as: 'questions_announcement_new'
  get '/completed_assignments/:assignment_id/new', to: 'responses#new', as: 'completed_assignments_assignment_new'

  # withdraw a student/teacher from a course
  get '/courses_users/:course_id/:student_id/destroy', to: 'courses_users#destroy', as: 'courses_user'
  
  # courses for student/teacher
  get '/teachers/:teacher_id/courses', to: 'courses#courses_for_teacher', as: 'courses_for_teacher'
  get '/students/:student_id/courses', to: 'courses#courses_for_student', as: 'courses_for_student'

  # students/teachers for course
  get '/courses/:course_id/students', to: 'users#students_for_course', as: 'students_for_course'
  get '/courses/:course_id/teachers', to: 'users#teachers_for_course', as: 'teachers_for_course'

  # auths
  get '/auth/twitter/callback', to: 'sessions_twitter#create'
  get '/signout_twitter', to: 'sessions_twitter#destroy'
  get '/signin_twitter_choose', to: 'users#choose', as: 'signin_twitter_choose'
  
end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  before_action :set_interaction, only: [:show, :edit, :update, :destroy]

  def index
    @index_title = title_by_path
    @interactions = interactions_by_path
  end

  def show
    # TODO: is it better to formulate this here instead of the view?
    # @children_label = @interaction.responses.first.type.pluralize.split(/(?=[A-Z])/).join(' ') unless @interaction.responses.empty?
  end

  def new
    @interaction = if title_by_path == "Announcements"
                     Announcement.new
                   elsif title_by_path == "Assignments"
                     Assignment.new
                   else
                     Interaction.new
                   end
    @interaction.course_id = params[:course_id] if params[:course_id]

    @interaction.user = current_user if logged_in?
  end

  def edit; end

  def create
    @interaction = Interaction.new(interaction_params)

    respond_to do |format|
      if @interaction.save
        format.html { redirect_to @interaction, notice: 'Creation successful' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @interaction.update(interaction_params)
        format.html { redirect_to @interaction, notice: 'Update successful' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @interaction.destroy
        format.html { redirect_to @interaction.course, notice: 'Deletion successful' }
      else
        format.html { redirect_to @interaction.course, notice: 'Error on deletion' }
      end
    end
  end

  private
    def set_interaction
      @interaction = Interaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # TODO: can you make this only deal with an interaction?
    def interaction_params
      if params[:announcement]
        params.require(:announcement).permit(:course_id, :user_id, :type, :title, :due_date, :graded, :points, :instructions)
      elsif params[:assignment]
        params.require(:assignment).permit(:course_id, :user_id, :type, :title, :due_date, :graded, :points, :instructions)
      else
        params.require(:interaction).permit(:course_id, :user_id, :type, :title, :due_date, :graded, :points, :instructions)
      end
    end

    def title_by_path
      if request.path.include?("announcements")
        "Announcements"
      elsif request.path.include?("assignments")
        "Assignments"
      else
       "Interactions"
      end
    end

    def interactions_by_path
      if title_by_path == "Announcements"
        Announcement.all
      elsif title_by_path == "Assignments"
        Assignment.all
      else
        Interaction.all
      end
    end
end

app/views/interactions/edit.html.erb
<div class="full">
  <main class="main">
    <p id="notice"><%= notice %></p>
    
    <%= render :partial => 'interaction_parent_info', locals: { interaction: @interaction } %>

    <% if @interaction && @interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interaction.errors.count, "error") %> prohibited this interaction from being saved:</h2>

      <ul>
        <% @interaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with url: "/interactions/#{@interaction.id}", model: @interaction, local: true, method: "patch" do |form| %>

    <%= form.hidden_field :type, value: @interaction.type %>

    <%= form.hidden_field :id, value: @interaction.id %>

    <%= form.hidden_field :course_id, value: @interaction.course.id %>

    <%= form.hidden_field :user_id, value: @interaction.user.id %>
    
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <% if @interaction.type != 'Announcement' %>
    <div class="field date-select">
      <%= form.label :due_date %>
      <%= form.date_select :due_date %>
    </div>
    <div class="field graded">
      <%= form.label :graded %>
      <%= form.check_box :graded %>
    </div>
    <div class="field points">
      <%= form.label :points %>
      <%= form.number_field :points %>
    </div>
    <div class="field">
      <%= form.label :instructions %>
      <%= text_area(:assignment, :instructions, value: @interaction.instructions, cols: 20, rows: 40) %>
    </div>
    <% end %>

    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>

    </div>
  </main>
</div>

app/views/interactions/index.html.erb
<div class="full">
  <main class="main">
    <h1><%= @index_title ? @index_title : "Interactions" =%></h1>
    <p id="notice"><%= notice %></p>
    <% if !@interactions.empty? %>
    <table>
      
      <thead>
        <tr>
          <th>Course</th>
          <th>Title</th>
          <% if @interactions.first.type != 'Announcement' %>
          <th>Due date</th>
          <th>Graded</th>
          <th>Points</th>
          <th>Completed Assts</th>
          <% else %>
          <th>Questions</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @interactions.each do |interaction| %>
        <tr>
          <td><%= link_to interaction.course.name, course_path(interaction.course) %></td>
          <td><%= link_to interaction.title, interaction_path(interaction) %></td>
          <% if interaction.type != 'Announcement' %>
          <td><%= interaction.due_date %></td>
          <td><%= interaction.graded %></td>
          <td><%= interaction.points %></td>
          <% end %>
          <td><%= interaction.responses.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <%= render :partial => "none" %>
    <% end %>
  </main>
</div>

app/views/interactions/new.html.erb
<div class="full">
  <main class="main">

    <p id="notice"><%= notice %></p>

    <%= render :partial => 'interaction_parent_info', locals: { interaction: @interaction } %>

    <% if @interaction && @interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interaction.errors.count, "error") %> prohibited this <%=@interaction.type.downcase%> from
        being saved:</h2>

      <ul>
        <% @interaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with url: "/interactions", model: @interaction, local: true, method: "post" do |form| %>

    <%= form.hidden_field :type, :value => @interaction.type %>

    <%= form.hidden_field :course_id, :value => @interaction.course_id %>

    <%= form.hidden_field :user_id, :value => @interaction.user_id %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <% if @interaction.type != 'Announcement' %>

    <div class="field date-select">
      <%= form.label :due_date %>
      <%= form.date_select :due_date %>
    </div>

    <div class="field graded">
      <%= form.label :graded %>
      <%= form.check_box :graded %>
    </div>

    <div class="field">
      <%= form.label :points %>
      <%= form.number_field :points %>
    </div>

    <div class="field">
      <%= form.label :instructions %>
      <%= text_area(:assignment, :instructions, cols: 20, rows: 40) %>
    </div>

    <% end %>

    <div class="actions">
      <%= form.submit %>
    </div>

    <% end %>
  </main>
</div>

app/views/interactions/show.html.erb
<div class="full">
  <main class="main">

    <p id="notice"><%= notice %></p>

    <%= render :partial => 'interaction_parent_info', locals: { interaction: @interaction } %>

    <div class="field">
      <label for="title">Title</label>
      <div id="title"><%= @interaction.title %></div>
    </div>

    <% if @interaction.type != "Announcement" %>
    <div class="field">
      <label for="due_date">Due Date</label>
      <div id="due_date"><%= @interaction.due_date %></div>
    </div>

    <div class="field">
      <label for="graded">Graded</label>
      <div id="graded"><%= @interaction.graded %></div>
    </div>

    <div class="field">
      <label for="points">Points</label>
      <div id="points"><%= @interaction.points %></div>
    </div>

    <div class="field">
      <label for="instructions">Instructions</label>
      <div id="instructions"><%= @interaction.instructions %></div>
    </div>
    <% end %>

    <% if logged_in? && (is_teacher_of?(@interaction.course) || is_enrolled_in?(@interaction.course)) %>
    <div class="field">
      <label for="<%= @interaction.responses_type %>"><%= @interaction.responses_type %></label>
      <% if !@interaction.responses.empty? %>
      <div id="<%= @interaction.responses_type %>">
        <% @interaction.responses.each do |response| %>
          <div>
            <%= response.content + " - " if response.type == "Question" %><%= link_to response.user.user_name, user_path(response.user) %> on <%= link_to response.created_at.strftime("%m/%d/%Y"), response_path(response) %>
            <% if response.type == "CompletedAssignment" %>
              <% if response.score || response.letter_grade %>
                - graded
              <% else %>
                - ungraded
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <% else %>
      <%= render :partial => "none" %>
      <% end %>
    </div>
    <% end %>

    <% if logged_in? %>
    <div class="actions">
      
      <% if is_teacher_of?(@interaction.course) %>
        <%= link_to "Edit #{@interaction.type.downcase}", edit_interaction_path(@interaction) %> | <%= link_to "Delete #{@interaction.type.downcase}" , interaction_path(@interaction), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>

      <!-- TODO: simplify this -->
      <% if is_enrolled_in?(@interaction.course) %>
        <% if @interaction.type == 'Announcement' %>
          <%= link_to "Ask question", questions_announcement_new_path(@interaction) %>
        <% elsif @interaction.type == 'Assignment' %>
          <% assignment_completed = CompletedAssignment.all.find_by(interaction: @interaction, user: current_user) %>
          <% if assignment_completed && !assignment_completed.graded %>
            <%= link_to "Edit your completed assignment", edit_response_path(assignment_completed) %>
            <%= link_to "Complete assignment", completed_assignments_assignment_new_path(@interaction) %>
          <% elsif assignment_completed && assignment_completed.graded %>
            <%= link_to "Completed assignment", response_path(assignment_completed) %>
          <% else %>
            <%= link_to "Complete assignment", completed_assignments_assignment_new_path(@interaction) %>
          <% end %>
        <% end %>
      <% end %>

    </div>
    <% end %>
  </main>
</div>