config/routes.rb
Rails.application.routes.draw do
  
  root 'layouts#index'

  # various course listings
  get '/courses/free', to: 'courses#free', as: 'courses_free'
  get '/courses/featured', to: 'courses#featured', as: 'courses_featured'
  get '/courses/featured/free', to: 'courses#featured_free', as: 'courses_featured_free'
  
  resources :courses do
    resources :comments
  end

  resources :users
  resources :teachers, controller: 'users'
  resources :students, controller: 'users'

  resources :interactions #TODO remove
  resources :announcements, controller: 'interactions'
  resources :assignments, controller: 'interactions'
  resources :responses #TODO remove
  resources :questions, controller: 'responses'
  resources :completed_assignments, controller: 'responses'

  get '/welcome', to: 'layouts#welcome'

  get '/signin', to: 'users#signin'

  get '/signout', to: 'users#signout'

  get '/post_signin', to: 'users#post_signin'

  get '/signup', to:'users#new'

  #randomize user avatar
  get '/users/:id/randomize_avatar', to: 'users#randomize_avatar'

  # new announcement/assignment for a course
  get '/announcements/:course_id/new', to: 'interactions#new', as: 'announcements_course_new'
  get '/assignments/:course_id/new', to: 'interactions#new', as: 'assignments_course_new'
  
  # new question/completed_assignment for an interaction (assignment/announcement)
  get '/questions/:announcement_id/new', to: 'responses#new', as: 'questions_announcement_new'
  get '/completed_assignments/:assignment_id/new', to: 'responses#new', as: 'completed_assignments_assignment_new'

  # withdraw a student/teacher from a course
  get '/courses_users/:course_id/:student_id/destroy', to: 'courses_users#destroy', as: 'courses_user'
  
  # courses for student/teacher
  get '/teachers/:teacher_id/courses', to: 'courses#courses_for_teacher', as: 'courses_for_teacher'
  get '/students/:student_id/courses', to: 'courses#courses_for_student', as: 'courses_for_student'

  # students/teachers for course
  get '/courses/:course_id/students', to: 'users#students_for_course', as: 'students_for_course'
  get '/courses/:course_id/teachers', to: 'users#teachers_for_course', as: 'teachers_for_course'

  # auths
  get '/auth/twitter/callback', to: 'sessions_twitter#create'
  get '/signout_twitter', to: 'sessions_twitter#destroy'
  get '/signin_twitter_choose', to: 'users#choose', as: 'signin_twitter_choose'
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  belongs_to :avatar

  has_and_belongs_to_many :courses

  has_many :responses, dependent: :destroy
  has_many :completed_assignments, -> { where type: "CompletedAssignment" }, source: :response
  has_many :questions, -> { where type: "Question" }, source: :response

  has_many :interactions, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  has_many :courses_commented_on, through: :comments, source: :course

  validates :user_name, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false, allow_nil: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :type, inclusion: { in: ["Student", "Teacher"], message: "must be teacher or student" }

  def self.teacher_student
    @users = []
    teacher = Teacher.new
    teacher.type = "Teacher"
    teacher.save
    @users.push(teacher)
    student = Student.new
    student.type = "Student"
    student.save
    @users.push(student)
    @users
  end

  def self.create_with_omniauth_twitter(auth_params, is_student)
    
    user = User.new

    if auth_params['info']
      user.user_name = auth_params['info']['nickname'] || ""
      user.first_name = (auth_params['info']['name'] || "").split(" ").first
      user.last_name = (auth_params['info']['name'] || "").split(" ").second
      user.email = auth_params['info']['email'] || nil
    end

    user.provider = auth_params['provider']
    user.uid = auth_params['uid']
    user.type = is_student ? 'Student' : 'Teacher'
    user.avatar = Avatar.unused_avatar
    user.password_digest = SecureRandom.urlsafe_base64
    
    # TODO: this doesn't seem very safe
    user.save
    user
  end
end

app/controllers/users_controller.rb
# rubocop:disable ClassLength
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :randomize_avatar]	
  
  def new
    @user = User.new
    @select_users = User.teacher_student
  end

  def show
    @user = User.find(params[:id])
  end

  def signin
    @select_users = User.teacher_student
  end

  def index
    
    @users ||= if request.path == "/students"
                Student.all
               else
                Teacher.all
               end
          
  end
    
  def render_index
    respond_to do |format|
      format.html { render :index }
    end
  end

  def students_for_course
    @course = Course.find_by(:id => params[:course_id])
    @users = @course.students
    render_index
  end
  
  def post_signin
    @user = User.find_by(:user_name => params[:user_name])

    # TODO: do this better somehow
    p = nil
    begin
      p = @user.authenticate(params[:password])
    rescue
      p = nil
    end

    if(@user && p)
        respond_to do |format|
          session[:user_id] = @user.id
          format.html { redirect_to courses_path, notice: 'Welcome to SkillCraft, a place to craft your skills'}
        end
    else
        respond_to do |format|
          format.html { redirect_to signin_path, notice: 'User name or password incorrect'}
        end
    end
  end
  
  def create
    @user = User.new(user_params)
    @user.avatar = Avatar.unused_avatar
    @matched_course_based_on_code = nil
    assign_course_to_user_based_on_code
    if @user.errors.full_messages.empty? && @user.save
      path = @user.type == "Student" ? student_path(@user) : teacher_path(@user)
      redirect_to path, notice: "#{@user.type} was successfully created"
    else #if they entered a course code, repopulate form
      @course_code = @matched_course_based_on_code.code if @matched_course_based_on_code
      @select_users = User.teacher_student
      respond_to do |format|
        format.html { render :new }
      end
    end
  end

  def update
    @user.attributes = user_params
    @matched_course_based_on_code = nil
    assign_course_to_user_based_on_code
    respond_to do |format|
      if @user.errors.count.zero? && @user.save
        format.html { redirect_to @user, notice: "#{@user.user_name} was successfully updated" }
      else
        @course_code = @matched_course_based_on_code.code if @matched_course_based_on_code
        format.html { render :edit }
      end
    end
  end

  def signout
    
    respond_to do |format|
      session[:user_id] = nil #using session.clear interfered with flash messages being displayed
      format.html { redirect_to root_path, notice: 'Come back soon!'}
    end

  end
  
  def randomize_avatar 
    @user.avatar = Avatar.unused_avatar
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(@user), notice: "#{@user.user_name} was successfully updated" }
      else
        format.html { render :edit }
      end
    end
  end

  def edit
    respond_to do |format|
      if logged_in? && @user == current_user
        @user = @user.becomes(User)
        format.html { render :edit }
      else
        format.html { redirect_to user_path(@user), notice: "Users cannot edit others" }
      end
    end
  end

  def destroy
    respond_to do |format|
      @user.destroy
      if @user.type == "Student"
        format.html { redirect_to students_url, notice: "Deletion successful" }
      else
        format.html { redirect_to teachers_url, notice: "Deletion successful" }
      end
    end
  end
  
  private

    def assign_course_to_user_based_on_code
      unless params[:code].blank?
        @matched_course_based_on_code = Course.find_by(:code => params[:code])
        if @matched_course_based_on_code
          @user.courses << @matched_course_based_on_code unless @user.courses.include?(@matched_course_based_on_code)
        else
          @user.validate
          @user.errors.add(:course, 'code incorrect')
        end
      end
    end
  
    def set_user
      @user = User.find(params[:id])
    end
        
    # Only allow a list of trusted parameters through.
    def user_params
      if params[:teacher]
        params.require(:teacher).permit(:user_name, :id, :password, :first_name, :last_name, :email, :type)
      elsif params[:student]
        params.require(:student).permit(:user_name, :id, :password, :first_name, :last_name, :email, :type)          
      elsif params[:user]
        params.require(:user).permit(:user_name, :id, :password, :first_name, :last_name, :email, :type)
      end
    end

end
# rubocop:enable ClassLength

app/views/users/choose.html.erb
<div class="full">
    <main class="main">
        <p id="notice"><%= notice %></p>
        <h2>Sign in with twitter</h2>
        <div class="field">
            <div style="text-align: center;">As a <a href='/auth/twitter?type=Teacher'>Teacher</a> or as a <a href='/auth/twitter?type=student'>Student</a></div>
        </div>
    </main>
</div>

app/views/users/edit.html.erb
<div class="full">
  <main class="main">

    <p id="notice"><%= notice %></p>

    <h1>Editing <%= @user.type %></h1>
    
    <% if @user && @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with model: @user, local: true, method: "patch" do |form| %>
    <%= form.hidden_field :type, value: @user.type %>
    <%= form.hidden_field :id, :value => @user.id%>
    
    <div class="field">
      <div class='avatar-wrapper'>
        <div class='avatar-container'>
          <%= cl_image_tag(@user.avatar.url)  %>
        </div>
        <a href="/users/<%=@user.id%>/randomize_avatar">randomize</a>
      </div>
    </div>

    <div class="field">
      <%= form.label :user_name %>
      <%= form.text_field :user_name %>
    </div>

    <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <label for="courses"><%= @user.type == "Student" ? "Courses enrolled" : "Courses taught" %></label>
      <div id="courses">
        <% if !@user.courses.empty? %>
          <% @user.courses.each do |course| %>
            <div><%= link_to course.name, course_path(course)%> < <%= link_to 'Withdraw', courses_user_path(course, @user) %></div>
          <% end %>
        <% else %>
          <div>No courses</div>
        <% end %>
      </div>
    </div>

    <div class="field">
      <label for='code'><%= @user.type == 'Student' ? 'Enroll in' : 'Teach' %> course (enter course code)</label>
      <% if @course_code %>
      <%= text_field(nil, :code, value: @course_code) %>
      <% else %>
      <%= text_field(nil, :code) %>
      <% end %>
    </div>

    <div class="actions">
      <%= submit_tag "Update" %>
    </div>

    <% end %>

    <div class="actions">
      <%= link_to 'Courses', courses_path %>
    </div>

  </main>
</div>

app/views/users/index.html.erb
<div class="full">
  <main class="main">
    <p id="notice"><%= notice %></p>
    
    <% if @course %>
    <div class="parent_info">
      <h1>Students</h1>
      <div>enrolled in the <strong>course</strong>: <%= link_to @course.name, course_path(@course) %></div>
    </div>
    <% else %>
    <div class="parent_info">
      <h1><%= @users.first.type.pluralize(@users.count) %></h1>
    </div>
    <% end %>

    <div class='course-listing-wrapper'>
      <% if !@users.empty? %>
        <% @users.each do |user| %>
        <div class="course-listing-item">

          <div class="field">
            <div class='subject-wrapper'>
              <div class='subject-wrapper-sm'>
                <%= link_to cl_image_tag(user.avatar.url), user %>
              </div>
            </div>
          </div>

          <div class="field">
            <div id="name" class="course-listing-name"><%= link_to user.user_name, user %></div>
          </div>

          <div class="field">
            <div class="course-listing-desc"><em><%= user.first_name %> <%= user.last_name %></em></div>
          </div>

          <div class="course-listing-item-details">
            <ul>

              <!-- TODO: what is the best way? -->
              
              <!-- 1. This is the most simple. All these "ifs" though. ugh. -->
              
              <!-- <% if user.type == "Student" %>
                <label>Courses enrolled</label>
              <% else %>
                <label>Courses taught</label>
              <% end %>
              <% if !user.courses.empty? %>
                <% if user.type == "Student" %>
                  <%= link_to user.courses.count, courses_for_student_path(user) %>
                <% else %>
                  <%= link_to user.courses.count, courses_for_teacher_path(user) %>
                <% end %>
              <% else %>
                <%= user.courses.count %>
              <% end %> -->
              
              
              <!-- 2. Attempting to get to the least amount of lines.
                      Not using helper to write the link, not good. 
                      Relies on @courses_title being passed
                      -->
              
              <!-- <li>
                <label><%= @courses_title %></label>
                <% if !user.courses.empty? %>
                <a href="/<%= user.type.downcase.pluralize %>/<%= user.id %>/courses"><%= user.courses.count %></a>
                <% else %>
                  <%= user.courses.count %>
                <% end %>
              </li> -->
              

              <!-- 3. Use a partial with locals -->
              <!--  Looks nicer here in the view, but /views/application/_associated_courses.html.erb still iffy.
                    This doesn't lessen the number of lines of code
                    Is use of locals unnecessarily complex?
                    -->
              <li>
              <%= render :partial => 'associated_courses', locals: { user: user } %>
              </li>

              <% if logged_in? && !user.email.blank? %>
              <li>
                <label>Email</label>
                <%= mail_to user.email, user.email %>
              <li>
              <% end %>

            </ul>
          </div>
        </div>
        <% end %>
      <% else %>
        <%= render :partial => "none" %>
      <% end %>
    </div>
  </main>
</div>

app/views/users/login.html.erb
<div class="full">
  <main class="main">
    <p id="notice"><%= notice %></p>
    <h1>Login</h1>
    <% if @user && @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with url: "/post_login", model: @user, local: true, method: "get" do |form| %>

    <%= form.hidden_field :type, :value => 'User'%>

    <div class="field">
      <%= form.label :user_name %>
      <%= form.text_field :user_name %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.text_field :password %>
    </div>

    <div class="actions">
      <%= submit_tag "Login" %>
    </div>

    <div class="signin-twitter-or">-OR-</div>

    <div class="signin-twitter-wrapper">
      <%= link_to image_tag("https://res.cloudinary.com/fergusdev/image/upload/v1589306122/skillcraft/sign-in-with-twitter-gray-png-img-fullhd-medium.png.img.fullhd.medium_z3ei0p.png", border: 0), signin_twitter_path %>
    </div>
    <% end %>

  </main>
</div>

app/views/users/new.html.erb
<div class="full">
  <main class="main">

    <p id="notice"><%= notice %></p>

    <h1>Sign up</h1>

    <% if @user && @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with url: "/users", model: @user, local: true, method: "post" do |form| %>

    <div class="field">
      <%= form.label :user_name %>
      <%= form.text_field :user_name %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= password_field(:user, :password, size: 20) %>
    </div>

    <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <label for="email">Join course (enter code)</label>
      <% if @course_code %>
      <%= text_field(nil, :code, value: @course_code) %>
      <% else %>
      <%= text_field(nil, :code) %>
      <% end %>
    </div>

    <div class="field">
      <label for="user_type">I am a</label>
      <%= collection_select(:user, :type, @select_users, :type, :type, include_blank: '-Please select-')%>
    </div>

    <div class="actions">
      <%= submit_tag "Sign up" %>
    </div>
    <% end %>
  </main>
</div>

app/views/users/show.html.erb
<div class="full">
    <main class="main">
  
      <p id="notice"><%= notice %></p>
  
      <h1>Show <%= @user.type %></h1>
      
      <div class="field">
        <div class='avatar-wrapper'>
          <div class='avatar-container'>
            <%= cl_image_tag(@user.avatar.url)  %>
          </div>
        </div>
      </div>
      
      <div class="field">
        <label for="user_name">User name</label>
        <div id="user_name"><%= @user.user_name %></div>
      </div>
      
      <div class="field">
        <label for="first_name">First name</label>
        <div id="first_name"><%= @user.first_name %></div>
      </div>

      <div class="field">
        <label for="last_name">Last name</label>
        <div id="last_name"><%= @user.last_name %></div>
      </div>

      <% if logged_in? %>
      <div class="field">
        <label for="email">Email</label>
        <div id="email"><%= mail_to @user.email, @user.email %></div>
      </div>
      
      <div class="field">
        <label for="courses"><%= @user.type == "Student" ? "Courses enrolled" : "Courses taught" %></label>
        <% if !@user.courses.empty? %>
        <div id="courses">
          <% @user.courses.each do |course| %>
            <div><%= link_to course.name, course %><% if logged_in? && is_teacher_of?(course) || current_user == @user %> < <%=link_to @user.type == "Student" ? 'Withdraw' : 'Stop teaching', courses_user_path(course, @user) %><% end %></div>
          <% end %>
        </div>
        <% else %>
        <%= render :partial => "none" %>
        <% end %>
      </div>
      
      <% if @user.type == "Student" %>
      <div class="field">
        <label for="courses_completed_assignments">Completed assignments</label>
        <% if !@user.completed_assignments.empty? %>
        <div id="courses_completed_assignments">
          <% @user.completed_assignments.each do |completed_assignment| %>
            <div><%= link_to completed_assignment.interaction.course.name, completed_assignment.interaction.course %> - <%= link_to completed_assignment.interaction.title, completed_assignment.interaction %> on <%= link_to completed_assignment.updated_at.strftime("%m/%d/%Y"), completed_assignment %><%= completed_assignment.graded ? ' - graded' : ' - ungraded' %></div>
          <% end %>
        </div>
        <% else %>
        <%= render :partial => "none" %>
        <% end %>
      </div>
      <div class="field">
        <label for="courses_questions_asked">Questions</label>
        <% if !@user.questions.empty? %>
        <div id="courses_questions_asked">
          <% @user.questions.each do |question| %>
            <div><%= link_to question.interaction.course.name, question.interaction.course %> - <%= link_to question.content, question %> on <%= link_to question.updated_at.strftime("%m/%d/%Y"), question %></div>
          <% end %>
        </div>
        <% else %>
        <%= render :partial => "none" %>
        <% end %>
      </div>
      <div class="field">
        <label for="courses_commented_on">Courses commented on</label>
        <% if !@user.courses_commented_on.empty? %>
        <div id="courses_commented_on">
          <% @user.courses_commented_on.each do |course| %>
            <% course.comments.each do |comment| %>
            <% if comment.user == @user %>
            <div><%= link_to course.name, course %> - <%= link_to comment.content, course_path(comment.course) %> on <%= link_to comment.created_at.strftime("%m/%d/%Y"), course_path(comment.course) %></div>
            <% end %>
            <% end %>
          <% end %>
        </div>
        <% else %>
        <%= render :partial => "none" %>
        <% end %>
      </div>
      <% end %>
      <% end %>
      
      <% if @user == current_user %>
      <div class="actions">
        <%= link_to "Edit #{@user.type.downcase}", edit_user_path %> | 
        <%= link_to "Delete #{@user.type.downcase}", @user, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %>
  
    </main>
  </div>

app/views/users/signin.html.erb
<div class="full">
  <main class="main">
    <p id="notice"><%= notice %></p>
    <h1>Sign in</h1>
    <% if @user && @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with url: "/post_signin", model: @user, local: true, method: "get" do |form| %>

    <div class="field">
      <%= form.label :user_name %>
      <%= form.text_field :user_name %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <!-- TODO: is this right to pass nil for object, trying to get this: 
           input size="20" type="password" name="password" id="password"> -->
      <%= password_field(nil, :password, size: 20) %>
    </div>

    <div class="actions">
      <%= submit_tag "Sign in" %>
    </div>

    <div class="signin-twitter-or">-OR-</div>

    <div class="signin-twitter-wrapper">
      <%= link_to image_tag("https://res.cloudinary.com/fergusdev/image/upload/v1589306122/skillcraft/sign-in-with-twitter-gray-png-img-fullhd-medium.png.img.fullhd.medium_z3ei0p.png", border: 0), signin_twitter_choose_path %>
    </div>
    <% end %>

  </main>
</div>