config/routes.rb
Rails.application.routes.draw do
  
  root 'layouts#index'

  # various course listings
  get '/courses/free', to: 'courses#free', as: 'courses_free'
  get '/courses/featured', to: 'courses#featured', as: 'courses_featured'
  get '/courses/featured/free', to: 'courses#featured_free', as: 'courses_featured_free'
  
  resources :courses do
    resources :comments
  end

  resources :users
  resources :teachers, controller: 'users'
  resources :students, controller: 'users'

  resources :interactions #TODO remove
  resources :announcements, controller: 'interactions'
  resources :assignments, controller: 'interactions'
  resources :responses #TODO remove
  resources :questions, controller: 'responses'
  resources :completed_assignments, controller: 'responses'

  get '/welcome', to: 'layouts#welcome'

  get '/signin', to: 'users#signin'

  get '/signout', to: 'users#signout'

  get '/post_signin', to: 'users#post_signin'

  get '/signup', to:'users#new'

  #randomize user avatar
  get '/users/:id/randomize_avatar', to: 'users#randomize_avatar'

  # new announcement/assignment for a course
  get '/announcements/:course_id/new', to: 'interactions#new', as: 'announcements_course_new'
  get '/assignments/:course_id/new', to: 'interactions#new', as: 'assignments_course_new'
  
  # new question/completed_assignment for an interaction (assignment/announcement)
  get '/questions/:announcement_id/new', to: 'responses#new', as: 'questions_announcement_new'
  get '/completed_assignments/:assignment_id/new', to: 'responses#new', as: 'completed_assignments_assignment_new'

  # withdraw a student/teacher from a course
  get '/courses_users/:course_id/:student_id/destroy', to: 'courses_users#destroy', as: 'courses_user'
  
  # courses for student/teacher
  get '/teachers/:teacher_id/courses', to: 'courses#courses_for_teacher', as: 'courses_for_teacher'
  get '/students/:student_id/courses', to: 'courses#courses_for_student', as: 'courses_for_student'

  # students/teachers for course
  get '/courses/:course_id/students', to: 'users#students_for_course', as: 'students_for_course'
  get '/courses/:course_id/teachers', to: 'users#teachers_for_course', as: 'teachers_for_course'

  # auths
  get '/auth/twitter/callback', to: 'sessions_twitter#create'
  get '/signout_twitter', to: 'sessions_twitter#destroy'
  get '/signin_twitter_choose', to: 'users#choose', as: 'signin_twitter_choose'
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :set_course, only: [:show, :edit, :update, :destroy]
  
  def index
    @courses = Course.all
  end

  def show
    @comment = Comment.find_by(user: current_user, course: @course)
  end

  def new
    @course = Course.new
    @course.code ||= @course.code = 4.times.map{rand(4)}.join
  end

  def edit; end

  def create
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Updated successful' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @course.destroy
        format.html { redirect_to courses_url, notice: 'Deletion successful' }
      else
        format.html { redirect_to courses_url, notice: 'Error on course deletion' }
      end
    end
  end

  def render_index
    respond_to do |format|
      format.html { render :index }
    end
  end

  def free
    @courses = Course.free
    render_index
  end

  def featured
    @courses = Course.featured
    render_index
  end

  def featured_free
    @courses = Course.featured.free
    render_index
  end

  def courses_for_teacher
    @courses = Teacher.find(params[:teacher_id]).courses
    render_index
  end

  def courses_for_student
    @courses = Student.find(params[:student_id]).courses
    render_index
  end

  private
  
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :image_url, :tuition_cost, :code, :featured, :short_desc, :long_desc, comments_attributes: [:id, :user_id, :course_id, :content])
  end

end

app/views/courses/edit.html.erb
<div class="full">
  <main class="main">

    <p id="notice"><%= notice %></p>

    <h1>Editing Course</h1>

    <% if @course && @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with url: "/courses/#{@course.id}", model: @course, local: true, method: "patch" do |form| %>

    <%= form.hidden_field :type, :value => 'Course'%>

    <%= form.hidden_field :id, :value => @course.id%>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :image_url %>
      <%= form.text_field :image_url %>
    </div>

    <div class="field course-tuition-cost">
      <%= form.label :tuition_cost %>
      <%= form.text_field :tuition_cost %>
    </div>

    <div class="field featured">
      <%= form.label :featured %>
      <%= check_box 'course', 'featured', {}, 'true', 'false' %>
    </div>
    
    <div class="field">
      <%= form.label :short_desc, "Short description" %>
      <%= form.text_field :short_desc %>
    </div>

    <div class="field">
      <%= form.label :long_desc, "Long description" %>
      <%= text_area(:course, :long_desc, value: @course.long_desc, cols: 20, rows: 40) %>
    </div>

    <div class="field">
      <label for="announcements">Announcements</label>
      <div id='announcements'>
        <% if !@course.announcements.empty? %>
          <% @course.announcements.each do |announcement| %>
            <div>Posted date: <%=announcement.created_at.strftime("%m/%d/%Y") %> - <%= link_to announcement.title, announcement_path(announcement)%> - <%= pluralize(announcement.questions.count, "question") %> asked</div>
          <% end %>
        <% else %>
        <%= render :partial => "none" %>
        <% end %>
      </div>
    </div>

    <div class="field">
      <label for="assignments">Assignments</label>
      <div id='assignmentes'>
        <% if !@course.assignments.empty? %>
          <% @course.assignments.each do |assignment| %>
            <div>Due date: <%=assignment.due_date.strftime("%m/%d/%Y") %> - <%= link_to assignment.title, assignment_path(assignment)%> - <%= pluralize(assignment.completed_assignments.count, "assignment") %> completed</div>
          <% end %>
        <% else %>
        <%= render :partial => "none" %>
        <% end %>
      </div>
    </div>

    <div class="field">
      <label for="teachers">Teachers</label>
      <div id="teachers">
        <% if !@course.teachers.empty? %>
          <% @course.teachers.each do |teacher| %>
            <div><%= link_to teacher.user_name, teacher_path(teacher)%> < <%= link_to "Withdraw", courses_user_path(@course,teacher) %></div>
          <% end %>
        <% else %>
        <%= render :partial => "none" %>
        <% end %>
      </div>
    </div>

    <div class="field">
      <label for="students">Students</label>
      <div id='students'>
        <% if !@course.students.empty? %>
          <% @course.students.each do |student| %>
            <div><%= link_to student.user_name, student_path(student)%> < <%= link_to "Withdraw", courses_user_path(@course,student) %></div>
          <% end %>
        <% else %>
        <%= render :partial => "none" %>
        <% end %>
      </div>
    </div>
    <div class="field">
      <label for="students">Student comments</label>
      <% if !@course.comments.empty? %>
        <%= form.fields_for :comments do |fc| %>
          <!-- https://apidock.com/rails/ActiveRecord/Persistence/becomes -->
          <!-- TODO better way? -->
          <% comment = fc.object.becomes(Comment) %>
          <div class="course-comments">  
            <div class="course-comment-content-wrapper">
            <% if comment.id.blank? %>
            <div class="course-add-new-comment">Add new comment:</div>
            <% else %>
            <div class="course-user">On <%= link_to comment.created_at.strftime("%m/%d/%Y"), edit_course_path(comment.course) %> <%= link_to comment.user.user_name, comment.user %> commented:</div>
            <% end %>
            <%= fc.hidden_field :id %>
            <%= fc.hidden_field :user_id %>
            <%= fc.hidden_field :course_id %>
            <%= fc.text_field :content %>
            </div>
            <div class="course-comment-delete">
              <% if !comment.id.blank? %>
              < <%= link_to 'Delete', course_comment_path(comment.course, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
      <%= render :partial => "none" %>
      <% end %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>

    <% if logged_in? && is_teacher_of?(@course) %>
    <div class="actions">
      <%= link_to 'Add Announcement', announcements_course_new_path(@course) %> | 
      <%= link_to 'Add Assignment', assignments_course_new_path(@course) %> |
      <%= link_to 'Delete course', @course, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <% end %>

  </main>
</div>

app/views/courses/index.html.erb
<div class="full">
  <main class="main">
    <p id="notice"><%= notice %></p>

    <h1>Courses</h1>

    <div class='course-listing-wrapper'>
      <% if !@courses.empty? %>
      <% @courses.each do |course| %>
      <div class="course-listing-item<%= course.featured ? " course-listing-item-featured" : "" %>">
        
        <div class="field">
          <div class='subject-wrapper'>
            <div class='subject-wrapper-sm'>
              <%= link_to cl_image_tag(course.image_url), course %>
            </div>
          </div>
        </div>
        
        <div class="field">
          <div id="name" class="course-listing-name"><%= link_to course.name, course %></div>
        </div>

        <div class="field">
          <div class="course-listing-desc"><em><%= course.short_desc %></em></div>
        </div>

        <div class="course-listing-item-details">
          <ul>
            <% if !course.teachers.empty? %>
            <li><label>Instructor</label> <%= link_to course.teachers.first.user_name, course.teachers.first %></li>
            <% else %>
            <li><label>Instructor</label> None</li>
            <% end %>
            <li><label>Tuition</label> <%= number_to_currency(course.tuition_cost) %></li>
            <li><label>Announcements</label> <%= course.announcements.count %></li>
            <li><label>Questions</label> <%= course.questions.count %></li>
            <li><label>Assignments</label> <%= course.assignments.count %></li>
            <li><label>Completed Assignments</label> <%= course.completed_assignments.count %></li>
            <li><label>Teacher count</label> <%= course.teachers.count %></li>
            <li>
              <label>Students enrolled</label>
              <% if !course.students.empty? %>
                <%= link_to course.students.count, students_for_course_path(course) %>
              <% else %>
                <%= course.students.count %>
              <% end %>
            </li>
            <% if logged_in? %>
            <li>
              <label>Student comments</label>
              <% if !course.students.empty? %>
                <%= link_to course.comments.count, course_comments_path(course) %>
              <% else %>
                <%= course.comments.count %>
              <% end %>
            </li>
            <% end %>
            <li class="course-listing-code">Code: <%= course.code %></li>
          </ul>
        </div>

      </div>
      <% end %>
      <% else %>
      <%= render :partial => "none" %>
      <% end %>
    </div>
    <div class="actions">
      <%= link_to 'All courses', courses_path %> | <%= link_to 'Featured courses', courses_featured_path %> | <%= link_to 'Free courses', courses_free_path %> | <%= link_to 'Featured/free courses', courses_featured_free_path %><% if logged_in? && !is_student? %> | <%= link_to 'New course', new_course_path %><% end %>
    </div>

  </main>
</div>

app/views/courses/new.html.erb
<div class="full">
  <main class="main">

    <p id="notice"><%= notice %></p>

    <h1>New Course</h1>

    <% if @course && @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with url: "/courses", model: @course, local: true, method: "post" do |form| %>

    <%= form.hidden_field :type, :value => 'Course'%>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :image_url %>
      <%= form.text_field :image_url %>
    </div>

    <div class="field course-tuition-cost">
      <%= form.label :tuition_cost %>
      <%= form.text_field :tuition_cost %>
    </div>
      
    <div class="field featured">
      <%= form.label :featured %>
      <!-- #TODO, why is this not form.check_box_tag -->
      <%= check_box 'course', 'featured', {}, 'true', 'false' %>
    </div>
      
    <div class="field">
      <%= form.label :short_desc, "Short description" %>
      <%= form.text_field :short_desc %>
    </div>
    
    <div class="field">
      <%= form.label :long_desc, "Long description" %>
      <%= text_area(:course, :long_desc, cols: 20, rows: 40) %>
    </div>
    
    <div class="field">
      <%= form.label :code %>
      <%= form.text_field :code %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>

  </main>
</div>

app/views/courses/show.html.erb
<div class="full">
  <main class="main">

    <p id="notice"><%= notice %></p>

    <div>
      <div class="subject-wrapper-med"><%= link_to cl_image_tag(@course.image_url), @course %></div>
    </div>

    <h1>Course: <%= @course.name %></h1>

    <div class="field">
      <label for="name">Course name</label>
      <div id="name"><%= @course.name %></div>
    </div>

    <div class="field">
      <label for="teachers">Teachers</label>
      <div id="teachers">
      <% if !@course.teachers.empty? %>
        <table class="course-user-listing">
        <% @course.teachers.each do |teacher| %>
          <tr>
            <td><div class='avatar-container-x-sm'><%= link_to cl_image_tag(teacher.avatar.url), teacher %></div></td>
            <td><%= link_to teacher.user_name, teacher_path(teacher)%></td>
          </tr>
        <% end %>
        </table>
      <% else %>
        <%= render :partial => "none" %>
      <% end %>
      </div>
    </div>

    <% if logged_in? %>
    <div class="field">
      <label for="name">Tuition cost</label>
      <div id="name"><%= number_to_currency(@course.tuition_cost) %></div>
    </div>

    <div class="field">
      <label for="code">Code</label>
      <div id="code"><%= @course.code %></div>
    </div>

    <div class="field">
      <label for="featured">Featured</label>
      <div id="featured"><%= @course.featured %></div>
    </div>
    <% end %>

    <div class="field">
      <label for="short_desc">Short description</label>
      <div id="short_desc"><%= @course.short_desc %></div>
    </div>

    <div class="field">
      <label for="long_desc">Long description</label>
      <div id="long_desc"><%= @course.long_desc %></div>
    </div>
    
    <% if logged_in? && is_enrolled_in?(@course) || is_teacher_of?(@course) %>

    <div class="field">
      <label for="announcements">Announcements</label>
      <div id="announcements">
      <% if !@course.announcements.empty? %>
        <% @course.announcements.each do |announcement| %>
          <div>Posted date: <%= announcement.created_at.strftime("%m/%d/%Y") %> - <%= link_to announcement.title, announcement_path(announcement) %> - <%= pluralize(announcement.questions.count, "question") %> asked</div>
        <% end %>
      <% else %>
        <%= render :partial => "none" %>
      <% end %>
      </div>
    </div>

    <div class="field">
      <label for="assignments">Assignments</label>
      <div id="assignments">
      <% if !@course.assignments.empty? %>
        <% @course.assignments.each do |assignment| %>
          <!-- TODO: why can't I refer to assignment.completed_assignments here? -->
          <div>Due date: <%= assignment.due_date.strftime("%m/%d/%Y") %> - <%= link_to assignment.title, assignment_path(assignment)%> - <%= pluralize(assignment.responses.count, "assignment") %> completed, <%= assignment.responses.find_all { |response| response.graded }.count %> graded</div>
        <% end %>
      <% else %>
        <%= render :partial => "none" %>
      <% end %>
      </div>
    </div>
    <% end %>

    <div class="field enrolled">
      <label for="students">Students enrolled</label>
      <div id="students">
        <% if !@course.students.empty? %>
          <div class="students-enrolled-count"><%= link_to @course.students.count, students_for_course_path(@course) %></div>
        <% else %>
          <%= render :partial => "none" %>
        <% end %>
      </div>
    </div>

    <% if logged_in? %>
    <div class="field">
      <label for="comments">Student comments</label>
      <div id="comments">
        <% if !@course.comments.empty? %>
        <% @course.comments.each do |comment| %>
          <div><%= link_to comment.content, edit_course_path(comment.course) %> - <%= link_to comment.user.user_name, comment.user %> on <%= comment.created_at.strftime("%m/%d/%Y") %></div>
        <% end %>
        <% else %>
          <%= render :partial => "none" %>
        <% end %>
      </div>
    </div>
    <% end %>
    
    <% if logged_in? && is_enrolled_in?(@course) %>
    <div class="actions">
      <% if has_commented_on?(@course) %>
        <%= link_to 'Update your course comment', edit_course_comment_path(@course, @comment) %> |
        <%= link_to 'Delete your course comment', course_comment_path(@course, @comment), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% else %>
        <%= link_to 'Add course comment', new_course_comment_path(@course) %>
      <% end %>
    </div>
    <% end %>

    <% if logged_in? && is_teacher_of?(@course) %>
    <div class="actions">
      <%= link_to 'Edit course', edit_course_path(@course) %> | 
      <%= link_to 'Delete course', @course, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'Add Announcement', announcements_course_new_path(@course) %> | 
      <%= link_to 'Add Assignment', assignments_course_new_path(@course) %>
    </div>
    <% end %>

  </main>
</div>