config/routes.rb
Rails.application.routes.draw do
  
  root 'layouts#index'

  # various course listings
  get '/courses/free', to: 'courses#free', as: 'courses_free'
  get '/courses/featured', to: 'courses#featured', as: 'courses_featured'
  get '/courses/featured/free', to: 'courses#featured_free', as: 'courses_featured_free'
  
  resources :courses do
    resources :comments
  end

  resources :users
  resources :teachers, controller: 'users'
  resources :students, controller: 'users'

  resources :interactions #TODO remove
  resources :announcements, controller: 'interactions'
  resources :assignments, controller: 'interactions'
  resources :responses #TODO remove
  resources :questions, controller: 'responses'
  resources :completed_assignments, controller: 'responses'

  get '/welcome', to: 'layouts#welcome'

  get '/signin', to: 'users#signin'

  get '/signout', to: 'users#signout'

  get '/post_signin', to: 'users#post_signin'

  get '/signup', to:'users#new'

  #randomize user avatar
  get '/users/:id/randomize_avatar', to: 'users#randomize_avatar'

  # new announcement/assignment for a course
  get '/announcements/:course_id/new', to: 'interactions#new', as: 'announcements_course_new'
  get '/assignments/:course_id/new', to: 'interactions#new', as: 'assignments_course_new'
  
  # new question/completed_assignment for an interaction (assignment/announcement)
  get '/questions/:announcement_id/new', to: 'responses#new', as: 'questions_announcement_new'
  get '/completed_assignments/:assignment_id/new', to: 'responses#new', as: 'completed_assignments_assignment_new'

  # withdraw a student/teacher from a course
  get '/courses_users/:course_id/:student_id/destroy', to: 'courses_users#destroy', as: 'courses_user'
  
  # courses for student/teacher
  get '/teachers/:teacher_id/courses', to: 'courses#courses_for_teacher', as: 'courses_for_teacher'
  get '/students/:student_id/courses', to: 'courses#courses_for_student', as: 'courses_for_student'

  # students/teachers for course
  get '/courses/:course_id/students', to: 'users#students_for_course', as: 'students_for_course'
  get '/courses/:course_id/teachers', to: 'users#teachers_for_course', as: 'teachers_for_course'

  # auths
  get '/auth/twitter/callback', to: 'sessions_twitter#create'
  get '/signout_twitter', to: 'sessions_twitter#destroy'
  get '/signin_twitter_choose', to: 'users#choose', as: 'signin_twitter_choose'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception #TODO: what is this?

  helper_method :logged_in?
  helper_method :current_user
  helper_method :is_student?
  helper_method :is_teacher?
  helper_method :is_teacher_of?
  helper_method :is_enrolled_in?
  helper_method :has_commented_on?
  helper_method :is_owner_of?
  
  private

  def logged_in?
    !!current_user
  end

  def is_student?
    @current_user && @current_user.type == "Student"
  end

  def is_teacher?
    @current_user && @current_user.type == "Teacher"
  end
    
  def current_user
    @current_user ||= User.find_by(:id => session[:user_id])
  end

  def is_teacher_of?(course)
    current_user && !course.teachers.empty? && course.teachers.include?(current_user)
  end

  def is_enrolled_in?(course)
    current_user && !course.students.empty? && course.students.include?(current_user)
  end

  def has_commented_on?(course)
    current_user && !course.comments.empty? && @course.comments.map(&:user_id).include?(current_user.id)
  end

  def is_owner_of?(response)
    current_user && response.user == current_user
  end

end

app/views/application/_actions.html.erb
<%= link_to 'Back', :back %>

app/views/application/_associated_courses.html.erb
<li>
  <% if user.type == "Student" %>
    Courses enrolled:
  <% else %>
    Courses taught:
  <% end %>
  <% if !user.courses.empty? %>
    <% if user.type == "Student" %>
      <%= link_to user.courses.count, courses_for_student_path(user) %>
    <% else %>
      <%= link_to user.courses.count, courses_for_teacher_path(user) %>
    <% end %>
  <% else %>
    <%= user.courses.count %>
  <% end %>
</li>

app/views/application/_interaction_parent_info.html.erb
<div class="parent_info">
  <h1><%= @interaction.type %></h1>
  <div>for the <strong>course</strong>: <%= link_to @interaction.course.name, course_path(@interaction.course) %></div>
  <% if @interaction.created_at && @interaction.user %>
  <div>by the <strong><%= @interaction.user.type.downcase %></strong>: <%= link_to @interaction.user.user_name, @interaction.user %> on <%= link_to @interaction.created_at.strftime("%m/%d/%Y"), interaction_path(@interaction) %></div>
  <% end %>
</div>

app/views/application/_none.html.erb
<div>None</div>

app/views/application/_parent_info.html.erb
<div style="text-align: center;margin: 1rem">addressed to the <%=@response.interaction.type%>:</div>
<div style="text-align: center;margin: 1rem">"<%= link_to @response.interaction.title, announcement_path(@response.interaction) %>"</div>

app/views/application/_response_parent_info.html.erb
<div class="parent_info">
  <h1><%= @response.type == "CompletedAssignment" ? "Complete Assignment": @response.type %></h1>
  <div>for the <strong><%= @response.interaction.type.downcase %></strong>: <%= link_to @response.interaction.title, announcement_path(@response.interaction) %></div>
  <div>as part of the <strong>course</strong>: <%= link_to @response.interaction.course.name, course_path(@response.interaction.course) %></div>
  <div>taught by <strong>teacher</strong>: <%= link_to @response.interaction.course.teachers.first.user_name, teacher_path(@response.interaction.course.teachers.first) %></div>
  <% if @response.type != "Question" %>
  <div><strong><%= response.interaction.type %></strong> Instructions:</div>
  <div><em><%= response.interaction.instructions %></em></div>
  <% end %>
  <div>submitted by <strong><%= @response.user.type.downcase %>:</strong> <%= link_to @response.user.user_name, student_path(@response.user) %></div>
</div>